### ISSUE TITLE
Can You help me in explaining how you manged to stick that navbar with continuous change in image background.

### ISSUE THREAD

**Issue by Geek-Tekina** [Brkgng/Brkgng#1]

**Comment by Brkgng** [comment]
@Geek-Tekina I have used `position: absolute` for achieve this. It is line 29 in main.css. Also used `left:50%` and `transform: translateX(-50%)` to make horizontal center navbar.
You can learn more about positioning here: https://developer.mozilla.org/en-US/docs/Web/CSS/position
or you can watch this tutorial: https://www.youtube.com/watch?v=jx5jmI0UlXU 
If you have more questions please don't hesitate to ask.

**Comment by Geek-Tekina** [comment]
Okay Thank You.
